"""empty message

Revision ID: 126c3a2178f6
Revises: cc45e4af4f9
Create Date: 2014-10-21 14:17:19.180510

"""

# revision identifiers, used by Alembic.
revision = '126c3a2178f6'
down_revision = 'cc45e4af4f9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stalks', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stalks')
    ### end Alembic commands ###
