"""empty message

Revision ID: 201baa351097
Revises: 4d3e495f6d60
Create Date: 2014-11-11 10:23:58.585453

"""

# revision identifiers, used by Alembic.
revision = '201baa351097'
down_revision = '4d3e495f6d60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
