"""empty message

Revision ID: 21a633e449ce
Revises: 201baa351097
Create Date: 2014-11-11 10:24:27.820066

"""

# revision identifiers, used by Alembic.
revision = '21a633e449ce'
down_revision = '201baa351097'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
