"""empty message

Revision ID: 2d696cdd68df
Revises: 388d0cc48e7c
Create Date: 2014-11-14 00:27:32.062569

"""

# revision identifiers, used by Alembic.
revision = '2d696cdd68df'
down_revision = '388d0cc48e7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
