"""empty message

Revision ID: 388d0cc48e7c
Revises: 21a633e449ce
Create Date: 2014-11-13 10:49:45.512414

"""

# revision identifiers, used by Alembic.
revision = '388d0cc48e7c'
down_revision = '21a633e449ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('hidden', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'hidden')
    ### end Alembic commands ###
