"""empty message

Revision ID: 47088f52a4ee
Revises: None
Create Date: 2015-05-04 22:48:32.691663

"""

# revision identifiers, used by Alembic.
revision = '47088f52a4ee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('passhash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('invite_key', sa.String(), nullable=True),
    sa.Column('join_time', sa.DateTime(), nullable=True),
    sa.Column('num_entries', sa.Integer(), nullable=True),
    sa.Column('combo', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.Integer(), nullable=True),
    sa.Column('secret_days', sa.Integer(), nullable=True),
    sa.Column('publicity', sa.Integer(), nullable=True),
    sa.Column('theme', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('stalks', sa.String(), nullable=True),
    sa.Column('latest_post_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('sid')
    )
    op.create_index(u'ix_user_combo', 'user', ['combo'], unique=False)
    op.create_index(u'ix_user_join_time', 'user', ['join_time'], unique=False)
    op.create_index(u'ix_user_latest_post_date', 'user', ['latest_post_date'], unique=False)
    op.create_index(u'ix_user_name', 'user', ['name'], unique=True)
    op.create_index(u'ix_user_num_entries', 'user', ['num_entries'], unique=False)
    op.create_index(u'ix_user_sid', 'user', ['sid'], unique=True)
    op.create_table('post',
    sa.Column('user_sid', sa.String(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('hidden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_sid'], ['user.sid'], ),
    sa.PrimaryKeyConstraint('user_sid', 'posted_date')
    )
    op.create_index(u'ix_post_posted_date', 'post', ['posted_date'], unique=False)
    op.create_index(u'ix_post_user_sid', 'post', ['user_sid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(u'ix_post_user_sid', table_name='post')
    op.drop_index(u'ix_post_posted_date', table_name='post')
    op.drop_table('post')
    op.drop_index(u'ix_user_sid', table_name='user')
    op.drop_index(u'ix_user_num_entries', table_name='user')
    op.drop_index(u'ix_user_name', table_name='user')
    op.drop_index(u'ix_user_latest_post_date', table_name='user')
    op.drop_index(u'ix_user_join_time', table_name='user')
    op.drop_index(u'ix_user_combo', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
