"""empty message

Revision ID: cc45e4af4f9
Revises: None
Create Date: 2014-10-09 18:21:59.939407

"""

# revision identifiers, used by Alembic.
revision = 'cc45e4af4f9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('color', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'color')
    op.drop_column('post', 'update_time')
    ### end Alembic commands ###
